### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by blakeembrey** [Gi60s/binary-case#1]
Hey! It's me (again) 😄 

I just wanted to let you know that I did end up doing lambda and I did _also_ end up needing this utility. However, there's a faster way to write the method. I ended up putting it here: https://github.com/blakeembrey/node-bit-string-mask/blob/master/src/index.ts (basically, the useful bit is doing bitwise logic instead of string coercion). I didn't need all the other functionality, just something small and fast and with TypeScript definitions included.

Side note: I ended up checking out what you used this with and I found https://www.npmjs.com/package/sans-server. Not sure if this will help you, but I've committed to a similar effort with https://github.com/blakeembrey/node-servie.

**Comment by Gi60s** [comment]
Blake, I'd like to start out by apologizing for not responding to this sooner. Somehow I missed the notification for this issue. 

Thank you for the code example. Your code is a substantial performance improvement that meets all of the requirements. I'm working on updating the binary-case code now to use your method. I've added a reference to you as the author within the index.js file.

Also, I took a look at Servie. That looks very interesting. Thank you for referencing it.
